# Generated by Django 3.0.5 on 2020-05-03 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0004_auto_20200503_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='foto_perfil',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
