# Generated by Django 3.0.5 on 2020-05-03 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_medico_foto_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='foto_perfil',
            field=models.ImageField(default='', upload_to='media'),
        ),
    ]
