# Generated by Django 3.0.5 on 2020-05-03 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_auto_20200503_0112'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='foto_perfil',
            field=models.ImageField(default='media/medicos/default.jpg', upload_to='media'),
        ),
    ]
