# Generated by Django 3.0.5 on 2020-05-03 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0007_auto_20200503_0116'),
    ]

    operations = [
        migrations.AddField(
            model_name='medico',
            name='genero',
            field=models.CharField(choices=[('F', 'Femenino'), ('M', 'Masculino')], default='M', max_length=20),
        ),
        migrations.AlterField(
            model_name='medico',
            name='foto_perfil',
            field=models.ImageField(default='media/medicos/default.jpg', upload_to='media/medicos'),
        ),
    ]
