# Generated by Django 3.0.6 on 2020-05-12 01:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_auto_20200503_0128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='foto_perfil',
            field=models.ImageField(default='medicos/default.jpg', upload_to='media/medicos'),
        ),
    ]
