# Generated by Django 3.0.6 on 2020-05-12 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_auto_20200511_2107'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medico',
            name='foto_perfil',
            field=models.ImageField(default='medicos/default.jpg', upload_to='medicos'),
        ),
    ]
