# Generated by Django 3.0.6 on 2020-05-14 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_auto_20200511_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita_medica',
            name='estado_cita',
            field=models.CharField(choices=[('DIS', 'Disponible'), ('SEL', 'Seleccionada'), ('RES', 'Reservada'), ('CONF', 'Confirmada'), ('ANUL', 'Anulada'), ('REA', 'Realizada')], default='DIS', max_length=20),
        ),
    ]
