# Generated by Django 3.0.6 on 2020-05-14 05:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_auto_20200514_0106'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cita_medica',
            name='paciente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.Paciente'),
        ),
    ]
