# Generated by Django 3.0.6 on 2020-05-19 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_auto_20200514_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='cita_medica',
            name='fecha_actualizacion',
            field=models.DateField(blank=True, null=True),
        ),
    ]
